### ISSUE TITLE
False positive: fp2e7a.wpc.2be4.phicdn.net

### ISSUE THREAD

**Issue by pathanin** [ttc-cert/TTC-CERT_blocklist_recommended#1]
`fp2e7a.wpc.2be4.phicdn.net` and `fp2e7a.wpc.phicdn.net` are the CNAMEs for `ocsp.digicert.com`, which is a legitimate service for checking for certificate revocation

```
# nslookup ocsp.digicert.com 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
ocsp.digicert.com	canonical name = ocsp.edge.digicert.com.
ocsp.edge.digicert.com	canonical name = fp2e7a.wpc.2be4.phicdn.net.
fp2e7a.wpc.2be4.phicdn.net	canonical name = fp2e7a.wpc.phicdn.net.
Name:	fp2e7a.wpc.phicdn.net
Address: 192.229.211.108
```

Reference:
https://github.com/hoshsadiq/adblock-nocoin-list/issues/452

**Comment by ttc-cert** [comment]
I'm grateful for your assistance in resolving the CNAME issue with fp2e7a.wpc.2be4.phicdn.net and fp2e7a.wpc.phicdn.net. Thanks to your expertise, we have confirmed that these CNAMEs are indeed associated with ocsp.digicert.com, a legitimate service for certificate revocation checks. This clarification has allowed us to confidently address the matter, and I'm pleased to inform you that the issue has been successfully resolved. Thank you for your support.
